# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'ACPLotteryProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ACPLotteryProject
#  use_frameworks!
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'Masonry'
  pod 'YYCache'
  pod 'SDCycleScrollView','~> 1.64'
  pod 'SVProgressHUD'
#  pod 'SDPhotoBrowser'
end
